##  Régression Logistique


### Contexte: 
Nous souhaitons mettre en place un modèle approprié permettant d'identifier le public cible pour une publicité spécifique sur l'un des réseaux sociaux, maximisant ainsi le taux de clics sur cette publicité.
### Description du Dataset
Notre Dataset 'Internautes_info.csv' contient des informations sur tous les utilisateurs du réseau social, y compris leur Identifiant, leur sexe, leur âge et leur salaire estimé. La dernière colonne de l'ensemble de données est un vecteur de booléens décrivant si chaque utilisateur a fini par cliquer sur la publicité (0 = Faux, 1 = Vrai).

In [1]:
# Importer les libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Importer le dataset

dataset = pd.read_csv('Internautes_info.csv')

In [3]:
#dimensions : nombre de lignes, nombre de colonnes
dataset.shape

(400, 5)

In [4]:
#Visualiser les 5 premiers
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
# diviser les données en attributs et étiquettes (labes)

X = dataset.iloc[:, [2,3]].values

y= dataset.iloc[:,4].values

In [6]:
# Splitting du dataset Training set and Test set (80%,20%)


from sklearn.model_selection import train_test_split
X_train, X_test, y__train, y_test=train_test_split(X,y, test_size=0.20)


In [7]:
# Feature Scaling (Mise en echelle)
from sklearn.preprocessing import MinMaxScaler, StandardScaler

minmaxscaler=MinMaxScaler()
X_train_n=minmaxscaler.fit_transform(X_train)
X_test_n=minmaxscaler.fit_transform(X_test)

standarscaler= StandardScaler()
X_train=standarscaler.fit_transform(X_train)
X_test=standarscaler.fit_transform(X_test)


C:\Users\Ines\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Ines\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
# Fitting Logistic Regression to the Training set

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,\
precision_score 

In [9]:
#on souhaite comparer les valeurs des métriques Accuracy et précision pour 
#les algorithmes LogisticRegression, KNN, SVM et DecisionTree
def classifier(X_train, X_test, y__train, y_test):
    
    clf1= LogisticRegression()
    clf1.fit(X_train_n, y__train)
    # Predicting the Test set results
    y_pred1= clf1.predict(X_test_n)
    # Making the Confusion Matrix
    cm1=confusion_matrix(y_test, y_pred1)
    print(cm1)
    print('Accuracy LR = ', format(accuracy_score(y_test, y_pred1)))
    print('Precision LR = ', format(precision_score(y_test, y_pred1)))
    
    
    clf2= KNeighborsClassifier(n_neighbors=5)
    clf2.fit(X_train_n, y__train)
    # Predicting the Test set results
    y_pred2= clf2.predict(X_test_n)
    # Making the Confusion Matrix
    cm2=confusion_matrix(y_test, y_pred2)
    print(cm2)
    print('Accuracy KNN = ', format(accuracy_score(y_test, y_pred2)))
    print('Precision KNN = ', format(precision_score(y_test, y_pred2)))
    
    
    clf3 = SVC(kernel='rbf')
    clf3.fit(X_train_n, y__train)
    # Predicting the Test set results
    y_pred3= clf3.predict(X_test_n)
    # Making the Confusion Matrix
    cm3=confusion_matrix(y_test, y_pred3)
    print(cm3)
    print('Accuracy SVM = ', format(accuracy_score(y_test, y_pred3)))
    print('Precision SVM = ', format(precision_score(y_test, y_pred3)))
    
    clf4 = DecisionTreeClassifier(criterion='entropy')
    clf4.fit(X_train_n, y__train)
    # Predicting the Test set results
    y_pred4= clf4.predict(X_test_n)
    # Making the Confusion Matrix
    cm4=confusion_matrix(y_test, y_pred4)
    print(cm4)
    print('Accuracy Decision Tree = ', format(accuracy_score(y_test, y_pred4)))
    print('Precision De ision Tree = ', format(precision_score(y_test, y_pred4)))
    
    return clf4
#appel de la fonction créee
clf4 = classifier(X_train_n, X_test_n, y__train, y_test)


[[51  1]
 [10 18]]
Accuracy LR =  0.8625
Precision LR =  0.9473684210526315
[[46  6]
 [ 2 26]]
Accuracy KNN =  0.9
Precision KNN =  0.8125
[[50  2]
 [ 7 21]]
Accuracy SVM =  0.8875
Precision SVM =  0.9130434782608695
[[39 13]
 [ 3 25]]
Accuracy Decision Tree =  0.8
Precision De ision Tree =  0.6578947368421053
